name: PlayArea
version: ${project.version}
main: me.jalawaquin.playarea.PlayArea
api-version: 1.13
authors: [Jalawaquin]
commands:
  setPlayArea:
    description: set the play area
    aliases: setplayarea
  deletePlayArea:
    description: delete the play area
    aliases: deleteplayarea
  modPlayArea:
    description: modify the play area
    aliases: modplayarea
  inPlayArea:
    description: modify the mob or potion effects when inside play area
    aliases: inplayarea