name: EffectZone
version: ${project.version}
main: me.jalawaquin.effectzone.EffectZone
api-version: 1.13
authors: [Jalawaquin]
commands:
  setEffectZone:
    description: set the effect zone
    aliases: seteffectzone
  deleteEffectZone:
    description: delete the effectzone
    aliases: deleteeffectzone
  turnEffectZone:
    description: turn effect zone modifications on and off
    aliases: turneffectzone
  insideEffectZone:
    description: modify the mob or potion effects when inside effect zone
    aliases: insideeffectzone
  outsidePlayArea:
    description: modify the mob or potion effects when inside effect zone
    aliases: outsideeffectzone