name: PlayArea
version: 1.0-SNAPSHOT
main: me.jalawaquin.playarea.PlayArea
api-version: 1.13
authors: [Jalawaquin]
commands:
  setPlayArea:
    description: set the play area
    aliases: setplayarea
  deletePlayArea:
    description: delete the play area
    aliases: deleteplayarea
  turnPlayArea:
    description: modify the play area
    aliases: turnplayarea
  inPlayArea:
    description: modify the mob or potion effects when inside play area
    aliases: inplayarea